### ISSUE TITLE
Dynamic view with components from multiple containers/software system

### ISSUE THREAD

**Issue by alleknalle** [structurizr-php/structurizr-php#65]
Hey there,

I would like to make a dynamic view with components from multiple containers and software systems. Structurizr supports this (from DSL), but this package doesn't.

In `src/StructurizrPHP/Core/View/DynamicView.php` in function `checkElement()` there are checks that make sure this can't be done. 

Is it possible to support this?

Sidenote 1: I've also seen the 'issue' that a lot of classes are final. Maybe this is a use case that I would like to extends the DynamicView class so that I can remove the checks.

Sidenote 2: it looks like it's not possible to create a 'landscape' dynamic view.
In Viewset there are only options for creating a DynamicView (by SoftwareSystem) or a ContainerDynamicView (by Container). 
When instantiating a new DynamicView without an element, the ViewSet is never connected to the DynamicView

**Comment by alleknalle** [comment]
I've created a Pull Request for this: https://github.com/structurizr-php/structurizr-php/pull/67

**Comment by norberttech** [comment]
this was merged thanks to @alleknalle contribution
