### ISSUE TITLE
Infrastructure node

### ISSUE THREAD

**Issue by alleknalle** [structurizr-php/structurizr-php#66]
Hey,

are you planning to add support for infrastructure nodes? Or is it already there by another name?

**Comment by alleknalle** [comment]
I've added support for infrastructure nodes in PR https://github.com/structurizr-php/structurizr-php/pull/70

**Comment by norberttech** [comment]
Awesome 🙌 will take a look over weekend, thanks!

**Comment by alleknalle** [comment]
@norberttech the actions are giving an error, I think on code style/format. Maybe you can help me with the correct settings, so I can use that on my machine

**Comment by norberttech** [comment]
could you please try to execute `composer cs:php:fix`? This should fix the coding standards and let you commit them into your pull request

**Comment by alleknalle** [comment]
Thanks, done :-)

**Comment by norberttech** [comment]
merged 👍

**Comment by norberttech** [comment]
https://github.com/structurizr-php/structurizr-php/releases/tag/0.2.0 this change is now available with several more things released as 0.2.0
